name: Build and deploy through Docker

on:
  workflow_dispatch:
  push:
    branches: ["main"]

# For built-in contexts, checkout https://docs.github.com/en/actions/learn-github-actions/contexts
env:
  REGISTRY: "git.liuyajie.com"
  # REGISTRY: ${{ var.REGISTRY || "gitea.com" }} Apply this after Gitea support actions->variable feature

jobs:
  # Build and push image to registry
  build-and-push:
    # https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job
    runs-on: [ubuntu-latest, X64]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Action digest
        run: |
          echo "🎉 The job was triggered by '${{ gitea.event_name }}' event on branch '${{ gitea.ref }}' of repository '${{ gitea.repository }}', running on '${{ runner.os }}/${{ runner.arch }}' runner."
          echo "Operating image '${{ env.REGISTRY }}/${{ gitea.repository }}'"

      - name: Check out repository code
        uses: actions/checkout@v3

      # https://gitea.com/gitea/act_runner/issues/301
      - name: "[Gitea] Install docker for ubuntu-latest runner"
        uses: papodaca/install-docker-action@main

      # https://gitea.com/gitea/act_runner/issues/303
      # https://github.com/marketplace/actions/docker-login
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY || "gitea.com" }}
          username: ${{ secrets.REGISTRY_USER || gitea.actor }}
          password: ${{ secrets.REGISTRY_TOKEN || secrets.GITEA_TOKEN }}

      # https://github.com/marketplace/actions/docker-metadata-action
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ gitea.repository }}
          # set latest tag for default branch
          tags: type=raw,value=latest,enable={{is_default_branch}}

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        # https://docs.gitea.com/usage/actions/comparison#dockerbuild-push-actionv4
        env:
          ACTIONS_RUNTIME_TOKEN: ""
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
